- name: Install base packages
  become: true
  ansible.builtin.package:
    name:
      - git
      - stow
      - fish
      - vim
      - neovim
      - tmux
      - ripgrep
      - fzf
    state: present
  ignore_errors: true
  when: ansible_distribution == 'Ubuntu'
