---
- name: Development Environment Setup
  hosts: localhost
  become: false

  tasks:

    - include_tasks: "{{item}}"
      loop: "{{ lookup('ansible.builtin.fileglob', 'tasks/base-setup/*.yaml', wantlist=True) }}"

    - include_tasks: "{{item}}"
      loop: "{{ lookup('ansible.builtin.fileglob', 'tasks/dotfiles/*.yaml', wantlist=True) }}"

    - include_tasks: "{{item}}"
      loop: "{{ lookup('ansible.builtin.fileglob', 'tasks/tree-sitter/*.yaml', wantlist=True) }}"

    - include_tasks: "{{item}}"
      loop: "{{ lookup('ansible.builtin.fileglob', 'tasks/neovim/*.yaml', wantlist=True) }}"

    - include_tasks: "{{item}}"
      loop: "{{ lookup('ansible.builtin.fileglob', 'tasks/window-manager/*.yaml', wantlist=True) }}"

    - include_tasks: "{{item}}"
      loop: "{{ lookup('ansible.builtin.fileglob', 'tasks/environment-variables/*.yaml', wantlist=True) }}"
