---
- name: Development Environment Setup
  hosts: localhost
  become: false
  vars:
    # the_user: "{{ ansible_user_id }}"
    base_packages:
      - git
      - stow
      - fish
      - vim
      - neovim
      - tmux
      - ripgrep
      - fzf

  tasks:
    - name: Install base packages
      become: true
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop: "{{ base_packages }}"
      ignore_errors: true

    # - name: Change shells for the current user
    #   become: true
    #   ansible.builtin.user:
    #     name: "{{ the_user }}"
    #     shell: /bin/fish

    - name: Checkout the latest dotfiles and symlink them.
      ansible.builtin.git:
        repo: "https://github.com/pedestrianlove/dotfiles.git"
        dest: "~/dotfiles"
        track_submodules: true

    - name: Setup the dotfiles.
      ansible.builtin.command: stow ~/dotfiles

    - name: Install tree-sitters
      become: true
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - tree-sitter
        - tree-sitter-cli
      when: ansible_distribution == 'Archlinux'
    - name: Install tree-sitters
      become: true
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - libtree-sitter0
        - libtree-sitter-dev
      when: ansible_distribution == 'Ubuntu'
