name: Test my Ansible playbook.

on: [push]

jobs:
  Test-my-playbook:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Setup Ansible
        run: |
          python -m pip install ansible
          ansible-galaxy collection install community.general
          ansible-galaxy collection install ansible.utils

      - name: Run ansible playbook
        run: |
          ansible-playbook setup.yaml
